userapp:
  replicaCount: 3
  server:
    port: 8000
  db:
    user: "userapp"
    password: "asdajlshdfljasdlkjasbdf"
    name: "userapp"
  auth_service:
    url: http://authapp-service.default.svc.cluster.local:8000
  billing_service:
    url: http://billingapp-service.default.svc.cluster.local:8000
  redpanda:
    addresses:
      - my-redpanda.default.svc.cluster.local:9093
    new_users_topic: new_users

authapp:
  replicaCount: 3
  server:
    port: 8000
  user_service:
    url: http://userapp-service.default.svc.cluster.local:8000
  jwt_token: 633TvE7i4SsFZvpNXRnv8q9MDd

kubernetes-ingress:
  prometheus:
    create: true
