replicaCount: 3

userapp:
  port: 8000
  db:
    user: "postgres"
    password: "userapp_password"
    name: "userapp"

kubernetes-ingress:
  prometheus:
    create: true
#kubernetes-ingress:
#  controller:
#    metrics:
#      enabled: true
#      serviceMonitor:
#        enabled: true
#        scrapeInterval: 10s
#        additionalLabels:
#          release: myprometheus
