architecture: replication
readReplicas:
  replicaCount: 1
auth:
  postgresPassword: "postgres_password"
  replicationPassword: "replica_password"
metrics:
  enabled: true
  service:
    annotations:
      nikita.ru/scrape_every_30s: "true"
      prometheus.io/port: "9187"
  image:
    repository: "bitnamilegacy/postgres-exporter"
image:
  repository: "bitnamilegacy/postgresql"

volumePermissions:
  image:
    repository: "bitnamilegacy/os-shell"


