apiVersion: v1
kind: Service
metadata:
  name: authapp-service
spec:
  type: NodePort
  ports:
    - port: {{ .Values.authapp.server.port }}
      targetPort: {{ .Values.authapp.server.port }}
      protocol: TCP
  selector:
    app: ryzhkov-authapp