apiVersion: v1
kind: ConfigMap
metadata:
  name: userapp-config
data:
  config.yaml: |
    database:
      username: {{ .Values.userapp.db.user }}
      password: {{ .Values.userapp.db.password }}
      host: pguser-postgresql-primary.default.svc.cluster.local
      port: 5432
      db_name: {{ .Values.userapp.db.name }}
    server:
      port: {{ .Values.userapp.server.port }}
    auth_service:
      url: {{ .Values.userapp.auth_service.url }}
    billing_service:
      url: {{ .Values.userapp.billing_service.url }}
    redpanda_broker:
      addresses: {{ .Values.userapp.redpanda.addresses}}
      new_users_topic: {{ .Values.userapp.redpanda.new_users_topic }}


