apiVersion: apps/v1
kind: Deployment
metadata:
  name: userapp-deployment
spec:
  replicas: {{ .Values.userapp.replicaCount }}
  selector:
    matchLabels:
      app: ryzhkov-userapp
  template:
    metadata:
      annotations:
        nikita.ru/scrape_every_30s: "true"
        prometheus.io/port: "{{ .Values.userapp.server.port }}"
      labels:
        app: ryzhkov-userapp
    spec:
      containers:
        - name: userapp
          image: kappy4uno/user_app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.userapp.server.port }}
          volumeMounts:
            - mountPath: /etc/userapp
              name: userappconfig
              readOnly: true
            - mountPath: /etc/pgsecret
              name: pgpassconfig
              readOnly: true
          livenessProbe:
            httpGet:
              port: {{ .Values.userapp.server.port }}
              path: /health
            initialDelaySeconds: 3
            periodSeconds: 1
          readinessProbe:
            httpGet:
              port: {{ .Values.userapp.server.port }}
              path: /health
            initialDelaySeconds: 3
            periodSeconds: 1
          startupProbe:
            httpGet:
              port: {{ .Values.userapp.server.port }}
              path: /health
            initialDelaySeconds: 3
            periodSeconds: 1
            failureThreshold: 30
      volumes:
        - name: userappconfig
          configMap:
            name: userapp-config
        - name: pgpassconfig
          secret:
            secretName: pguser-postgresql
