apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: userapp-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /otusapp/nryzhkov/(.*)
            backend:
              service:
                name: userapp-service
                port:
                  number: {{ .Values.userapp.port }}
            pathType: ImplementationSpecific

