apiVersion: batch/v1
kind: Job
metadata:
  name: userapp-initdb-job
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-50"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: userapp-initdb
      labels:
        app: ryzhkov-userapp-initdb
    spec:
      restartPolicy: OnFailure
      containers:
        - name: userapp-initdb
          image: kappy4uno/initdb:v0.0.5
          volumeMounts:
            - mountPath: /etc/initdb
              name: initdb-config
            - mountPath: /etc/pgsecret
              name: pg-secret
      volumes:
        - name: initdb-config
          configMap:
            name: userapp-config
        - name: pg-secret
          secret:
            secretName: pguser-postgresql
